version: '3'

services:
  api:
    build: .
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=test123
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
      - NODE_ENV=development
    ports:
      - 1337:1337
    volumes:
      - ./strapi-app/api:/usr/src/api/strapi-app/api
      - ./strapi-app/config:/usr/src/api/strapi-app/config
      - ./strapi-app/extensions:/usr/src/api/strapi-app/extensions
      - ./strapi-app/public:/usr/src/api/strapi-app/public
    depends_on:
      - postgres
    command: ["./strapi.sh"]
    restart: always
  postgres: 
    image: postgres:10.4
    restart: always
    volumes:
      - ./postgresdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=strapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
    ports:
      - 5432:5432